### PR TITLE
Support python stub files

### PR DESCRIPTION
**Pull request by JLLeitschuh**
- https://mypy.readthedocs.io/en/stable/stubs.html
- https://realpython.com/python-ellipsis/

Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Currently seeing this error. It looks like arguments are getting re-ordered, which looks like it's likely a problem outside the scope of this change?

```
org.opentest4j.AssertionFailedError: [When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error!] 
expected: 
  "# Variables with annotations do not need to be assigned a value.
  # So by convention, we omit them in the stub file.
  x: int
  
  # Function bodies cannot be completely removed. By convention,
  # we replace them with `...` instead of the `pass` statement.
  def func_1(code: str) -> int: ...
  
  # We can do the same with default arguments.
  def func_2(a: int, b: int = ...) -> int: ..."
 but was: 
  "# Variables with annotations do not need to be assigned a value.
  # So by convention, we omit them in the stub file.
  x: int
  
  # Function bodies cannot be completely removed. By convention,
  # we replace them with `...` instead of the `pass` statement.
  def func_1(code: str) -> int: ...
  
  # We can do the same with default arguments.
  def func_2(a: int, b = ...: int) -> int: ..."
```

**Review by garyolsen — APPROVED** [review]

**Comment by JLLeitschuh** [comment]
@garyolsen do you have any insights into why the arguments are getting re-ordered, which is causing the tests to fail? I have no insights here.

**Comment by garyolsen** [comment]
@JLLeitschuh Yes, this is unrelated—the implementation of type hints in our model is being rendered incorrectly when there is a default value for a parameter.

**Comment by JLLeitschuh** [comment]
Should that get fixed first before this gets merged then? Do you have the cycles to fix that?

**Comment by garyolsen** [comment]
I think it's fine to merge this first—I won't be able to look at the parsing/printing issue for at least a few days. Just omit the failing test for now and I'll add it back in when I fix the underlying issue.

**Comment by JLLeitschuh** [comment]
Sure, better to do it right than fast. What's the ETA?

**Comment by traceyyoshima** [comment]
> Sure, better to do it right than fast. What's the ETA?

Thank you - I agree. I created a PythonCoreApplicationEnvironment, but I am still sorting out how to configure dependencies and IntelliJ's virtual file system to resolve types. PYI files are set into a specific workspace, but I need to figure out how that happens. I need a few days to sort out the requirements and will provide an ETA afterward.

**Comment by JLLeitschuh** [comment]
If you've got a plan here, I think I'll close this pull request

**Pull request closed without merging**
